[2025-02-28T10:45:24.658+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-28T10:45:24.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.fetch_weather scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-02-28T10:45:24.753+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.fetch_weather scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-02-28T10:45:24.756+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-28T10:45:24.791+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather> on 2025-02-28 00:00:00+00:00
[2025-02-28T10:45:24.817+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl', 'fetch_weather', 'scheduled__2025-02-28T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpbqsp6f4e']
[2025-02-28T10:45:24.822+0000] {standard_task_runner.py:91} INFO - Job 105: Subtask fetch_weather
[2025-02-28T10:45:24.833+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=181) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T10:45:24.836+0000] {standard_task_runner.py:63} INFO - Started process 194 to run task
[2025-02-28T10:45:24.899+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl.fetch_weather scheduled__2025-02-28T00:00:00+00:00 [running]> on host 083d33cb466d
[2025-02-28T10:45:26.458+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='fetch_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T00:00:00+00:00'
[2025-02-28T10:45:26.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-28T10:45:29.184+0000] {logging_mixin.py:188} INFO - ⚠️ Lỗi khi lấy dữ liệu cho Hai Phong: 404 Client Error: Not Found for url: https://api.openweathermap.org/data/2.5/weather?appid=4c0ce10a03e3f9a54655917b0c81d3a9&q=Hai%20Phong,VN&units=metric
[2025-02-28T10:45:41.407+0000] {python.py:237} INFO - Done. Returned value was:     city_id         city_name country  ... visibility  dew_point  precipitation
0   1581130             Hanoi      VN  ...      10000        N/A              0
1   1566083  Ho Chi Minh City      VN  ...      10000        N/A              0
2   1583992             Turan      VN  ...      10000        N/A              0
3   1572151         Nha Trang      VN  ...      10000        N/A              0
4   1586203           Can Tho      VN  ...      10000        N/A              0
5   1562798              Vinh      VN  ...      10000        N/A              0
6   1580240               Hue      VN  ...      10000        N/A              0
7   1586896     Buon Ma Thuot      VN  ...      10000        N/A              0
8   1584071            Da Lat      VN  ...      10000        N/A              0
9   1568574          Qui Nhon      VN  ...      10000        N/A              0
10  1569684            Pleiku      VN  ...      10000        N/A              0
11  1566166         Thanh Hoa      VN  ...      10000        N/A              0
12  1566319       Thai Nguyen      VN  ...      10000        N/A              0
13  1591449          Bac Ninh      VN  ...      10000        N/A              0
14  1571058        Phan Thiet      VN  ...      10000        N/A              0
15  1574023            My Tho      VN  ...      10000        N/A              0
16  1568510          Rach Gia      VN  ...      10000        N/A              0
17  1580410           Ha Long      VN  ...      10000        N/A              0
18  1586443            Ca Mau      VN  ...      10000        N/A              0

[19 rows x 15 columns]
[2025-02-28T10:45:42.611+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-28T10:45:49.155+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl, task_id=fetch_weather, run_id=scheduled__2025-02-28T00:00:00+00:00, execution_date=20250228T000000, start_date=20250228T104524, end_date=20250228T104549
[2025-02-28T10:45:49.547+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-28T10:45:50.468+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
